name: Release Node.js app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish image to Docker Hub
    steps:
    # Checkout to the repository
    - uses: actions/checkout@v4
    
    # We need to login so we can later push the image without issues.
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    # Builds youngpickling/express-app-devops:latest
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: youngpickling/express-app-devops:latest